-- =====================================================
-- Blog & News Publishing Platform - Shared Schema
-- Run this once in phpMyAdmin
-- =====================================================

CREATE DATABASE IF NOT EXISTS blog_platform
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE blog_platform;

-- ---------- USERS ----------
CREATE TABLE IF NOT EXISTS users (
  id              INT AUTO_INCREMENT PRIMARY KEY,
  name            VARCHAR(100) NOT NULL,
  email           VARCHAR(150) NOT NULL UNIQUE,
  password_hash   VARCHAR(255) NOT NULL,
  role            ENUM('reader','author','admin') NOT NULL DEFAULT 'reader',
  pending_author  TINYINT(1) NOT NULL DEFAULT 0,
  bio             TEXT NULL,
  profile_pic_path VARCHAR(255) NULL,
  social_links    JSON NULL,
  remember_token  VARCHAR(255) NULL,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ---------- CATEGORIES ----------
CREATE TABLE IF NOT EXISTS categories (
  id   INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(80) NOT NULL UNIQUE
) ENGINE=InnoDB;

-- ---------- TAGS ----------
CREATE TABLE IF NOT EXISTS tags (
  id   INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(60) NOT NULL UNIQUE
) ENGINE=InnoDB;

-- ---------- ARTICLES ----------
CREATE TABLE IF NOT EXISTS articles (
  id                   INT AUTO_INCREMENT PRIMARY KEY,
  author_id            INT NOT NULL,
  category_id          INT NULL,
  title                VARCHAR(200) NOT NULL,
  body                 LONGTEXT NOT NULL,
  featured_image_path  VARCHAR(255) NULL,
  status               ENUM('draft','published') NOT NULL DEFAULT 'draft',
  publish_at           DATETIME NULL,
  view_count           INT NOT NULL DEFAULT 0,
  created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (author_id)   REFERENCES users(id)      ON DELETE CASCADE,
  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- ---------- ARTICLE_TAGS (pivot) ----------
CREATE TABLE IF NOT EXISTS article_tags (
  article_id INT NOT NULL,
  tag_id     INT NOT NULL,
  PRIMARY KEY (article_id, tag_id),
  FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE,
  FOREIGN KEY (tag_id)     REFERENCES tags(id)     ON DELETE CASCADE
) ENGINE=InnoDB;

-- ---------- LIKES ----------
CREATE TABLE IF NOT EXISTS likes (
  id         INT AUTO_INCREMENT PRIMARY KEY,
  article_id INT NOT NULL,
  user_id    INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_article_user (article_id, user_id),
  FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id)    REFERENCES users(id)    ON DELETE CASCADE
) ENGINE=InnoDB;

-- ---------- COMMENTS ----------
CREATE TABLE IF NOT EXISTS comments (
  id         INT AUTO_INCREMENT PRIMARY KEY,
  article_id INT NOT NULL,
  user_id    INT NOT NULL,
  body       TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id)    REFERENCES users(id)    ON DELETE CASCADE
) ENGINE=InnoDB;

-- ---------- REPORTED_COMMENTS ----------
CREATE TABLE IF NOT EXISTS reported_comments (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  comment_id  INT NOT NULL,
  reported_by INT NOT NULL,
  reason      VARCHAR(255) NOT NULL,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_comment_reporter (comment_id, reported_by),
  FOREIGN KEY (comment_id)  REFERENCES comments(id) ON DELETE CASCADE,
  FOREIGN KEY (reported_by) REFERENCES users(id)    ON DELETE CASCADE
) ENGINE=InnoDB;

-- ---------- SEED AN ADMIN (password = admin123) ----------
-- The hash below is for 'admin123' generated by password_hash()
INSERT INTO users (name, email, password_hash, role)
VALUES (
  'Admin',
  'admin@blog.local',
  '$2y$10$wH8u6F1l0Y2QY9F1V3JpH.5JzG7m6yQ2.tQ1Lq3Yk5Wd0aOQpDqOe',
  'admin'
)
ON DUPLICATE KEY UPDATE email = email;
